# data_ingestion.py parameters
multiplier: '1'
timespan: 'minute'
start_date: "2015-09-01"
end_date: "2025-09-01"

# data directories
input_dir: "data/raw_tickers_1-minute"
training_dir: "data/training_sets_1-minute"
validation_dir: "data/validation_sets_1-minute"

# list of tickers in use
tickers: [
                    "NVDA", "TSLA", "INTC", "AAPL", "AMZN", "GOOGL", "AMD", "AVGO", "MSFT",
                    "MRVL", "CSCO", "MU", "META", "SHOP", "QCOM", "MCHP", "ON",
                    "PYPL", "CRM", "ADBE", "NFLX"
                ]

# training splits for train.py
training_splits:
  training_1:
      - tickers: 
          - AMD 
          - NVDA
          - INTC 
        timesteps: 1380000
    
  training_2:
      - tickers: 
          - AMD 
          - NVDA
        timesteps: 450000
  
  training_3:
      - tickers: 
          - AMD 
        timesteps: 240000

  training_4:
      - tickers: 
          - NVDA
        timesteps: 210000

  training_5:
      - tickers: 
          - INTC 
        timesteps: 200000
  
  training_6:
      - tickers: 
          - AMD 
        timesteps: 240000

      - tickers: 
          - NVDA
        timesteps: 210000
  
  training_7:
      - tickers: 
          - AMD 
        timesteps: 240000

      - tickers: 
          - NVDA
        timesteps: 210000

      - tickers: 
          - INTC 
        timesteps: 200000
  
      
